#!/bin/bash

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 Как проверить сайт на другом устройстве"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🖥️  НАЙДИТЕ IP-АДРЕС ВАШЕГО КОМПЬЮТЕРА:"
echo ""

# Определяем операционную систему
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "🐧 Linux:"
    echo "   Команда: ip addr show | grep 'inet ' | grep -v '127.0.0.1'"
    echo ""
    echo "   Или используйте: hostname -I"
    echo ""
    ip addr show | grep 'inet ' | grep -v '127.0.0.1' | awk '{print "   IP: " $2}' || echo "   (команда недоступна)"
    
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "🍎 macOS:"
    echo "   Команда: ifconfig | grep 'inet ' | grep -v '127.0.0.1'"
    echo ""
    ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print "   IP: " $2}' || echo "   (команда недоступна)"
    
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "win32" ]]; then
    echo "🪟 Windows:"
    echo "   Команда: ipconfig | findstr IPv4"
    echo ""
    ipconfig 2>/dev/null | grep "IPv4" || echo "   Используйте команду 'ipconfig' в CMD"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 ШАГ ЗА ШАГОМ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Запустите сервер разработки:"
echo "    npm run dev"
echo ""
echo "2️⃣  Найдите IP-адрес компьютера (см. выше)"
echo "    Обычно это что-то вроде: 192.168.1.100"
echo ""
echo "3️⃣  Подключите телефон к той же Wi-Fi сети"
echo ""
echo "4️⃣  Откройте на телефоне браузер и введите:"
echo "    http://[ВАШ-IP]:3000"
echo "    Например: http://192.168.1.100:3000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔥 АЛЬТЕРНАТИВНЫЕ СПОСОБЫ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📲 Способ 2: Через QR код"
echo "   • Используйте сервис: https://www.qr-code-generator.com/"
echo "   • Введите ваш локальный URL"
echo "   • Отсканируйте QR код телефоном"
echo ""
echo "☁️  Способ 3: Через Cloudflare Tunnel (ngrok аналог)"
echo "   1. npm install -g cloudflared"
echo "   2. cloudflared tunnel --url http://localhost:3000"
echo "   3. Получите публичный URL"
echo ""
echo "🌍 Способ 4: Через ngrok"
echo "   1. Скачайте: https://ngrok.com/"
echo "   2. Запустите: ngrok http 3000"
echo "   3. Используйте публичный URL"
echo ""
echo "🚀 Способ 5: Задеплойте на Cloudflare Pages"
echo "   1. npm run build"
echo "   2. wrangler pages deploy dist"
echo "   3. Получите постоянный URL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  ВАЖНО:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "• Компьютер и телефон должны быть в одной Wi-Fi сети"
echo "• Firewall должен разрешать входящие соединения"
echo "• Порт 3000 должен быть открыт"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
